version: '3.1'

services:
  mongo:
    image: mongo:5.0.2
    hostname: mongo
    volumes: 
      - ./data/mongo:/data
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: sko-is-hot
    networks:
      - 'internal'

networks:
  internal:
    driver: 'bridge'